export const MASTER_CHOFERES = [
  'Tomás Casco', 'Iván Santillán', 'Gali Nelson', 'Juan Cruz Hidalgo', 
  'Matías Chaile', 'Vega Jorge Daniel', 'Christian González', 'VideoTest',
  'Leandro Rodriguez', 'Cristian Montenegro', 'Gustavo Arzamendia', 'Facundo Villalba',
  'Santiago Perez', 'Nahuel Maidana', 'Lucas Gomez', 'Enzo Maidana',
  'Kevin Maidana', 'Adrian Maidana', 'Federico Maidana', 'Jonathan Maidana',
  'Mariano Maidana', 'Oscar Maidana', 'Pedro Maidana', 'Ramon Maidana'
];

export const MASTER_VEHICULOS = [
  { patente: 'AD848KQ', proximoServiceKm: 534300 },
  { patente: 'PGX770', proximoServiceKm: 558100 },
  { patente: 'A124TJW', proximoServiceKm: 84500 },
  { patente: 'A122WRA', proximoServiceKm: 7300 },
  { patente: 'AD380TS', proximoServiceKm: 719700 },
  { patente: 'A239WDL', proximoServiceKm: 12700 },
  { patente: 'ONR078', proximoServiceKm: 417399 },
  { patente: 'AF601QS', proximoServiceKm: 282250 },
  { patente: 'PGX769', proximoServiceKm: 522200 },
  { patente: 'AD724VP', proximoServiceKm: 449299 },
  { patente: 'AF668JV', proximoServiceKm: 417600 },
  { patente: 'AF668JR', proximoServiceKm: 292150 },
  { patente: 'A239WDM', proximoServiceKm: 8200 },
  { patente: 'AD848LH', proximoServiceKm: 465700 },
  { patente: 'AD724VQ', proximoServiceKm: 537700 },
  { patente: 'AD848KR', proximoServiceKm: 534000 },
  { patente: 'AH279KZ', proximoServiceKm: 60000 },
  { patente: 'AH336BA', proximoServiceKm: 80000 }
];

export const MASTER_SUCURSALES = [
  { id: 1, nombre: 'Boedo' },
  { id: 4, nombre: 'San Martin' },
  { id: 5, nombre: 'Moron' },
  { id: 6, nombre: 'San Justo' },
  { id: 7, nombre: 'Ramos' },
  { id: 8, nombre: 'San Miguel' },
  { id: 9, nombre: 'Zarate' },
  { id: 10, nombre: 'Campana' },
  { id: 11, nombre: 'Pacheco' },
  { id: 12, nombre: 'Pacheco NOVO' },
  { id: 13, nombre: 'San Fernando' },
  { id: 14, nombre: 'San Isidro' },
  { id: 15, nombre: 'San Isidro ROLON' },
  { id: 16, nombre: 'Martinez' },
  { id: 17, nombre: 'Olivos' },
  { id: 18, nombre: 'Vicente Lopez' },
  { id: 19, nombre: 'TESO NORTE' },
  { id: 20, nombre: 'TESO SAN TELMO' },
  { id: 21, nombre: 'Belgrano' },
  { id: 22, nombre: 'Cabildo' },
  { id: 23, nombre: 'Barrio Norte' },
  { id: 24, nombre: 'Plaza Italia' },
  { id: 25, nombre: 'Parque Patricios' },
  { id: 26, nombre: 'Once' },
  { id: 29, nombre: 'Canning' },
  { id: 30, nombre: 'Monte Grande' },
  { id: 31, nombre: 'Adrogue' },
  { id: 32, nombre: 'Lomas' },
  { id: 33, nombre: 'Banfield' },
  { id: 34, nombre: 'Lanus' },
  { id: 35, nombre: 'Avellaneda' },
  { id: 36, nombre: 'Wilde' },
  { id: 37, nombre: 'Bernal' },
  { id: 38, nombre: 'Berazategui' },
  { id: 39, nombre: 'Varela' },
  { id: 40, nombre: 'Berisso' },
  { id: 41, nombre: 'La Plata 50' },
  { id: 42, nombre: 'La Plata 56' },
  { id: 43, nombre: 'Chascomus' },
  { id: 44, nombre: 'Gualeguaychú' },
  { id: 45, nombre: 'Concordia' },
  { id: 46, nombre: 'La Paz' },
  { id: 47, nombre: 'Olavarría' },
  { id: 48, nombre: 'Tandil' },
  { id: 49, nombre: 'Tres Arroyo' },
  { id: 50, nombre: 'Coronel Suarez' },
  { id: 51, nombre: 'Independencia (MDQ)' },
  { id: 52, nombre: 'Güemes (MDQ)' }
];
