// ... arriba igual ...
    if (res.success) {
      // CAMBIO: Ahora los manda a la pantalla de Waze/Sucursales usando el ID que creamos
      router.push("/driver/navigation/" + res.id);
    } else {
// ... resto igual ...
